sudo: false
language: node_js
node_js:
  - 4.1
  
branches:
  only:
    - gh-pages

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    # Remove once travis-multirunner can handle firefox again.
    - env: BROWSER:firefox BVER=stable
    - env: BROWSER:firefox BVER=beta
    - env: BROWSER=firefox BVER=nightly

before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done
